/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssistenteRouteImport } from './routes/api/assistente'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppVeiculosRouteImport } from './routes/_authenticated/app/veiculos'
import { Route as AuthenticatedAppUsuariosRouteImport } from './routes/_authenticated/app/usuarios'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app/relatorios'
import { Route as AuthenticatedAppReceberRouteImport } from './routes/_authenticated/app/receber'
import { Route as AuthenticatedAppPlanoContasRouteImport } from './routes/_authenticated/app/plano-contas'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app/perfil'
import { Route as AuthenticatedAppPagarRouteImport } from './routes/_authenticated/app/pagar'
import { Route as AuthenticatedAppMotoristasRouteImport } from './routes/_authenticated/app/motoristas'
import { Route as AuthenticatedAppManutencoesRouteImport } from './routes/_authenticated/app/manutencoes'
import { Route as AuthenticatedAppFornecedoresRouteImport } from './routes/_authenticated/app/fornecedores'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated/app/financeiro'
import { Route as AuthenticatedAppEmpresaRouteImport } from './routes/_authenticated/app/empresa'
import { Route as AuthenticatedAppDocumentosRouteImport } from './routes/_authenticated/app/documentos'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app/clientes'
import { Route as AuthenticatedAppAssistenteRouteImport } from './routes/_authenticated/app/assistente'
import { Route as AuthenticatedAppAlertasRouteImport } from './routes/_authenticated/app/alertas'
import { Route as AuthenticatedAppAbastecimentosRouteImport } from './routes/_authenticated/app/abastecimentos'
import { Route as AuthenticatedAppViagensIndexRouteImport } from './routes/_authenticated/app/viagens.index'
import { Route as AuthenticatedAppViagensIdRouteImport } from './routes/_authenticated/app/viagens.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistenteRoute = ApiAssistenteRouteImport.update({
  id: '/api/assistente',
  path: '/api/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVeiculosRoute =
  AuthenticatedAppVeiculosRouteImport.update({
    id: '/app/veiculos',
    path: '/app/veiculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppUsuariosRoute =
  AuthenticatedAppUsuariosRouteImport.update({
    id: '/app/usuarios',
    path: '/app/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/app/relatorios',
    path: '/app/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReceberRoute = AuthenticatedAppReceberRouteImport.update({
  id: '/app/receber',
  path: '/app/receber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPlanoContasRoute =
  AuthenticatedAppPlanoContasRouteImport.update({
    id: '/app/plano-contas',
    path: '/app/plano-contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/app/perfil',
  path: '/app/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPagarRoute = AuthenticatedAppPagarRouteImport.update({
  id: '/app/pagar',
  path: '/app/pagar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMotoristasRoute =
  AuthenticatedAppMotoristasRouteImport.update({
    id: '/app/motoristas',
    path: '/app/motoristas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppManutencoesRoute =
  AuthenticatedAppManutencoesRouteImport.update({
    id: '/app/manutencoes',
    path: '/app/manutencoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFornecedoresRoute =
  AuthenticatedAppFornecedoresRouteImport.update({
    id: '/app/fornecedores',
    path: '/app/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/app/financeiro',
    path: '/app/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmpresaRoute = AuthenticatedAppEmpresaRouteImport.update({
  id: '/app/empresa',
  path: '/app/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDocumentosRoute =
  AuthenticatedAppDocumentosRouteImport.update({
    id: '/app/documentos',
    path: '/app/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/app/clientes',
    path: '/app/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAssistenteRoute =
  AuthenticatedAppAssistenteRouteImport.update({
    id: '/app/assistente',
    path: '/app/assistente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAlertasRoute = AuthenticatedAppAlertasRouteImport.update({
  id: '/app/alertas',
  path: '/app/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAbastecimentosRoute =
  AuthenticatedAppAbastecimentosRouteImport.update({
    id: '/app/abastecimentos',
    path: '/app/abastecimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppViagensIndexRoute =
  AuthenticatedAppViagensIndexRouteImport.update({
    id: '/app/viagens/',
    path: '/app/viagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppViagensIdRoute =
  AuthenticatedAppViagensIdRouteImport.update({
    id: '/app/viagens/$id',
    path: '/app/viagens/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/app/abastecimentos': typeof AuthenticatedAppAbastecimentosRoute
  '/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/app/assistente': typeof AuthenticatedAppAssistenteRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/empresa': typeof AuthenticatedAppEmpresaRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/app/manutencoes': typeof AuthenticatedAppManutencoesRoute
  '/app/motoristas': typeof AuthenticatedAppMotoristasRoute
  '/app/pagar': typeof AuthenticatedAppPagarRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/plano-contas': typeof AuthenticatedAppPlanoContasRoute
  '/app/receber': typeof AuthenticatedAppReceberRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/viagens/$id': typeof AuthenticatedAppViagensIdRoute
  '/app/viagens/': typeof AuthenticatedAppViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/app/abastecimentos': typeof AuthenticatedAppAbastecimentosRoute
  '/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/app/assistente': typeof AuthenticatedAppAssistenteRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/app/empresa': typeof AuthenticatedAppEmpresaRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/app/manutencoes': typeof AuthenticatedAppManutencoesRoute
  '/app/motoristas': typeof AuthenticatedAppMotoristasRoute
  '/app/pagar': typeof AuthenticatedAppPagarRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/plano-contas': typeof AuthenticatedAppPlanoContasRoute
  '/app/receber': typeof AuthenticatedAppReceberRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/viagens/$id': typeof AuthenticatedAppViagensIdRoute
  '/app/viagens': typeof AuthenticatedAppViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/assistente': typeof ApiAssistenteRoute
  '/_authenticated/app/abastecimentos': typeof AuthenticatedAppAbastecimentosRoute
  '/_authenticated/app/alertas': typeof AuthenticatedAppAlertasRoute
  '/_authenticated/app/assistente': typeof AuthenticatedAppAssistenteRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/documentos': typeof AuthenticatedAppDocumentosRoute
  '/_authenticated/app/empresa': typeof AuthenticatedAppEmpresaRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/_authenticated/app/manutencoes': typeof AuthenticatedAppManutencoesRoute
  '/_authenticated/app/motoristas': typeof AuthenticatedAppMotoristasRoute
  '/_authenticated/app/pagar': typeof AuthenticatedAppPagarRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/plano-contas': typeof AuthenticatedAppPlanoContasRoute
  '/_authenticated/app/receber': typeof AuthenticatedAppReceberRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/usuarios': typeof AuthenticatedAppUsuariosRoute
  '/_authenticated/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/viagens/$id': typeof AuthenticatedAppViagensIdRoute
  '/_authenticated/app/viagens/': typeof AuthenticatedAppViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/api/assistente'
    | '/app/abastecimentos'
    | '/app/alertas'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/documentos'
    | '/app/empresa'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/manutencoes'
    | '/app/motoristas'
    | '/app/pagar'
    | '/app/perfil'
    | '/app/plano-contas'
    | '/app/receber'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app/'
    | '/app/viagens/$id'
    | '/app/viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/api/assistente'
    | '/app/abastecimentos'
    | '/app/alertas'
    | '/app/assistente'
    | '/app/clientes'
    | '/app/documentos'
    | '/app/empresa'
    | '/app/financeiro'
    | '/app/fornecedores'
    | '/app/manutencoes'
    | '/app/motoristas'
    | '/app/pagar'
    | '/app/perfil'
    | '/app/plano-contas'
    | '/app/receber'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/veiculos'
    | '/app'
    | '/app/viagens/$id'
    | '/app/viagens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/api/assistente'
    | '/_authenticated/app/abastecimentos'
    | '/_authenticated/app/alertas'
    | '/_authenticated/app/assistente'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/documentos'
    | '/_authenticated/app/empresa'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/fornecedores'
    | '/_authenticated/app/manutencoes'
    | '/_authenticated/app/motoristas'
    | '/_authenticated/app/pagar'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/plano-contas'
    | '/_authenticated/app/receber'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/usuarios'
    | '/_authenticated/app/veiculos'
    | '/_authenticated/app/'
    | '/_authenticated/app/viagens/$id'
    | '/_authenticated/app/viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAssistenteRoute: typeof ApiAssistenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistente': {
      id: '/api/assistente'
      path: '/api/assistente'
      fullPath: '/api/assistente'
      preLoaderRoute: typeof ApiAssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/veiculos': {
      id: '/_authenticated/app/veiculos'
      path: '/app/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AuthenticatedAppVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/usuarios': {
      id: '/_authenticated/app/usuarios'
      path: '/app/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AuthenticatedAppUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/app/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/receber': {
      id: '/_authenticated/app/receber'
      path: '/app/receber'
      fullPath: '/app/receber'
      preLoaderRoute: typeof AuthenticatedAppReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/plano-contas': {
      id: '/_authenticated/app/plano-contas'
      path: '/app/plano-contas'
      fullPath: '/app/plano-contas'
      preLoaderRoute: typeof AuthenticatedAppPlanoContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/app/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pagar': {
      id: '/_authenticated/app/pagar'
      path: '/app/pagar'
      fullPath: '/app/pagar'
      preLoaderRoute: typeof AuthenticatedAppPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/motoristas': {
      id: '/_authenticated/app/motoristas'
      path: '/app/motoristas'
      fullPath: '/app/motoristas'
      preLoaderRoute: typeof AuthenticatedAppMotoristasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/manutencoes': {
      id: '/_authenticated/app/manutencoes'
      path: '/app/manutencoes'
      fullPath: '/app/manutencoes'
      preLoaderRoute: typeof AuthenticatedAppManutencoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fornecedores': {
      id: '/_authenticated/app/fornecedores'
      path: '/app/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AuthenticatedAppFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/app/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/empresa': {
      id: '/_authenticated/app/empresa'
      path: '/app/empresa'
      fullPath: '/app/empresa'
      preLoaderRoute: typeof AuthenticatedAppEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/documentos': {
      id: '/_authenticated/app/documentos'
      path: '/app/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AuthenticatedAppDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/app/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assistente': {
      id: '/_authenticated/app/assistente'
      path: '/app/assistente'
      fullPath: '/app/assistente'
      preLoaderRoute: typeof AuthenticatedAppAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/alertas': {
      id: '/_authenticated/app/alertas'
      path: '/app/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AuthenticatedAppAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/abastecimentos': {
      id: '/_authenticated/app/abastecimentos'
      path: '/app/abastecimentos'
      fullPath: '/app/abastecimentos'
      preLoaderRoute: typeof AuthenticatedAppAbastecimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/viagens/': {
      id: '/_authenticated/app/viagens/'
      path: '/app/viagens'
      fullPath: '/app/viagens/'
      preLoaderRoute: typeof AuthenticatedAppViagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/viagens/$id': {
      id: '/_authenticated/app/viagens/$id'
      path: '/app/viagens/$id'
      fullPath: '/app/viagens/$id'
      preLoaderRoute: typeof AuthenticatedAppViagensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAbastecimentosRoute: typeof AuthenticatedAppAbastecimentosRoute
  AuthenticatedAppAlertasRoute: typeof AuthenticatedAppAlertasRoute
  AuthenticatedAppAssistenteRoute: typeof AuthenticatedAppAssistenteRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppDocumentosRoute: typeof AuthenticatedAppDocumentosRoute
  AuthenticatedAppEmpresaRoute: typeof AuthenticatedAppEmpresaRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppFornecedoresRoute: typeof AuthenticatedAppFornecedoresRoute
  AuthenticatedAppManutencoesRoute: typeof AuthenticatedAppManutencoesRoute
  AuthenticatedAppMotoristasRoute: typeof AuthenticatedAppMotoristasRoute
  AuthenticatedAppPagarRoute: typeof AuthenticatedAppPagarRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppPlanoContasRoute: typeof AuthenticatedAppPlanoContasRoute
  AuthenticatedAppReceberRoute: typeof AuthenticatedAppReceberRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppUsuariosRoute: typeof AuthenticatedAppUsuariosRoute
  AuthenticatedAppVeiculosRoute: typeof AuthenticatedAppVeiculosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppViagensIdRoute: typeof AuthenticatedAppViagensIdRoute
  AuthenticatedAppViagensIndexRoute: typeof AuthenticatedAppViagensIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAbastecimentosRoute: AuthenticatedAppAbastecimentosRoute,
  AuthenticatedAppAlertasRoute: AuthenticatedAppAlertasRoute,
  AuthenticatedAppAssistenteRoute: AuthenticatedAppAssistenteRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppDocumentosRoute: AuthenticatedAppDocumentosRoute,
  AuthenticatedAppEmpresaRoute: AuthenticatedAppEmpresaRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppFornecedoresRoute: AuthenticatedAppFornecedoresRoute,
  AuthenticatedAppManutencoesRoute: AuthenticatedAppManutencoesRoute,
  AuthenticatedAppMotoristasRoute: AuthenticatedAppMotoristasRoute,
  AuthenticatedAppPagarRoute: AuthenticatedAppPagarRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppPlanoContasRoute: AuthenticatedAppPlanoContasRoute,
  AuthenticatedAppReceberRoute: AuthenticatedAppReceberRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppUsuariosRoute: AuthenticatedAppUsuariosRoute,
  AuthenticatedAppVeiculosRoute: AuthenticatedAppVeiculosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppViagensIdRoute: AuthenticatedAppViagensIdRoute,
  AuthenticatedAppViagensIndexRoute: AuthenticatedAppViagensIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAssistenteRoute: ApiAssistenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
