/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppViagensRouteImport } from './routes/_authenticated/app/viagens'
import { Route as AuthenticatedAppVeiculosRouteImport } from './routes/_authenticated/app/veiculos'
import { Route as AuthenticatedAppReceberRouteImport } from './routes/_authenticated/app/receber'
import { Route as AuthenticatedAppPagarRouteImport } from './routes/_authenticated/app/pagar'
import { Route as AuthenticatedAppMotoristasRouteImport } from './routes/_authenticated/app/motoristas'
import { Route as AuthenticatedAppFornecedoresRouteImport } from './routes/_authenticated/app/fornecedores'
import { Route as AuthenticatedAppEmpresaRouteImport } from './routes/_authenticated/app/empresa'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated/app/clientes'
import { Route as AuthenticatedAppViagensIdRouteImport } from './routes/_authenticated/app/viagens.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppViagensRoute = AuthenticatedAppViagensRouteImport.update({
  id: '/app/viagens',
  path: '/app/viagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVeiculosRoute =
  AuthenticatedAppVeiculosRouteImport.update({
    id: '/app/veiculos',
    path: '/app/veiculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppReceberRoute = AuthenticatedAppReceberRouteImport.update({
  id: '/app/receber',
  path: '/app/receber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPagarRoute = AuthenticatedAppPagarRouteImport.update({
  id: '/app/pagar',
  path: '/app/pagar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMotoristasRoute =
  AuthenticatedAppMotoristasRouteImport.update({
    id: '/app/motoristas',
    path: '/app/motoristas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppFornecedoresRoute =
  AuthenticatedAppFornecedoresRouteImport.update({
    id: '/app/fornecedores',
    path: '/app/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmpresaRoute = AuthenticatedAppEmpresaRouteImport.update({
  id: '/app/empresa',
  path: '/app/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/app/clientes',
    path: '/app/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppViagensIdRoute =
  AuthenticatedAppViagensIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppViagensRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/empresa': typeof AuthenticatedAppEmpresaRoute
  '/app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/app/motoristas': typeof AuthenticatedAppMotoristasRoute
  '/app/pagar': typeof AuthenticatedAppPagarRoute
  '/app/receber': typeof AuthenticatedAppReceberRoute
  '/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/app/viagens': typeof AuthenticatedAppViagensRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/viagens/$id': typeof AuthenticatedAppViagensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/empresa': typeof AuthenticatedAppEmpresaRoute
  '/app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/app/motoristas': typeof AuthenticatedAppMotoristasRoute
  '/app/pagar': typeof AuthenticatedAppPagarRoute
  '/app/receber': typeof AuthenticatedAppReceberRoute
  '/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/app/viagens': typeof AuthenticatedAppViagensRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/viagens/$id': typeof AuthenticatedAppViagensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/empresa': typeof AuthenticatedAppEmpresaRoute
  '/_authenticated/app/fornecedores': typeof AuthenticatedAppFornecedoresRoute
  '/_authenticated/app/motoristas': typeof AuthenticatedAppMotoristasRoute
  '/_authenticated/app/pagar': typeof AuthenticatedAppPagarRoute
  '/_authenticated/app/receber': typeof AuthenticatedAppReceberRoute
  '/_authenticated/app/veiculos': typeof AuthenticatedAppVeiculosRoute
  '/_authenticated/app/viagens': typeof AuthenticatedAppViagensRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/viagens/$id': typeof AuthenticatedAppViagensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/clientes'
    | '/app/empresa'
    | '/app/fornecedores'
    | '/app/motoristas'
    | '/app/pagar'
    | '/app/receber'
    | '/app/veiculos'
    | '/app/viagens'
    | '/app/'
    | '/app/viagens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app/clientes'
    | '/app/empresa'
    | '/app/fornecedores'
    | '/app/motoristas'
    | '/app/pagar'
    | '/app/receber'
    | '/app/veiculos'
    | '/app/viagens'
    | '/app'
    | '/app/viagens/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/empresa'
    | '/_authenticated/app/fornecedores'
    | '/_authenticated/app/motoristas'
    | '/_authenticated/app/pagar'
    | '/_authenticated/app/receber'
    | '/_authenticated/app/veiculos'
    | '/_authenticated/app/viagens'
    | '/_authenticated/app/'
    | '/_authenticated/app/viagens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/viagens': {
      id: '/_authenticated/app/viagens'
      path: '/app/viagens'
      fullPath: '/app/viagens'
      preLoaderRoute: typeof AuthenticatedAppViagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/veiculos': {
      id: '/_authenticated/app/veiculos'
      path: '/app/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AuthenticatedAppVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/receber': {
      id: '/_authenticated/app/receber'
      path: '/app/receber'
      fullPath: '/app/receber'
      preLoaderRoute: typeof AuthenticatedAppReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pagar': {
      id: '/_authenticated/app/pagar'
      path: '/app/pagar'
      fullPath: '/app/pagar'
      preLoaderRoute: typeof AuthenticatedAppPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/motoristas': {
      id: '/_authenticated/app/motoristas'
      path: '/app/motoristas'
      fullPath: '/app/motoristas'
      preLoaderRoute: typeof AuthenticatedAppMotoristasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/fornecedores': {
      id: '/_authenticated/app/fornecedores'
      path: '/app/fornecedores'
      fullPath: '/app/fornecedores'
      preLoaderRoute: typeof AuthenticatedAppFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/empresa': {
      id: '/_authenticated/app/empresa'
      path: '/app/empresa'
      fullPath: '/app/empresa'
      preLoaderRoute: typeof AuthenticatedAppEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/app/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/viagens/$id': {
      id: '/_authenticated/app/viagens/$id'
      path: '/$id'
      fullPath: '/app/viagens/$id'
      preLoaderRoute: typeof AuthenticatedAppViagensIdRouteImport
      parentRoute: typeof AuthenticatedAppViagensRoute
    }
  }
}

interface AuthenticatedAppViagensRouteChildren {
  AuthenticatedAppViagensIdRoute: typeof AuthenticatedAppViagensIdRoute
}

const AuthenticatedAppViagensRouteChildren: AuthenticatedAppViagensRouteChildren =
  {
    AuthenticatedAppViagensIdRoute: AuthenticatedAppViagensIdRoute,
  }

const AuthenticatedAppViagensRouteWithChildren =
  AuthenticatedAppViagensRoute._addFileChildren(
    AuthenticatedAppViagensRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppEmpresaRoute: typeof AuthenticatedAppEmpresaRoute
  AuthenticatedAppFornecedoresRoute: typeof AuthenticatedAppFornecedoresRoute
  AuthenticatedAppMotoristasRoute: typeof AuthenticatedAppMotoristasRoute
  AuthenticatedAppPagarRoute: typeof AuthenticatedAppPagarRoute
  AuthenticatedAppReceberRoute: typeof AuthenticatedAppReceberRoute
  AuthenticatedAppVeiculosRoute: typeof AuthenticatedAppVeiculosRoute
  AuthenticatedAppViagensRoute: typeof AuthenticatedAppViagensRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppEmpresaRoute: AuthenticatedAppEmpresaRoute,
  AuthenticatedAppFornecedoresRoute: AuthenticatedAppFornecedoresRoute,
  AuthenticatedAppMotoristasRoute: AuthenticatedAppMotoristasRoute,
  AuthenticatedAppPagarRoute: AuthenticatedAppPagarRoute,
  AuthenticatedAppReceberRoute: AuthenticatedAppReceberRoute,
  AuthenticatedAppVeiculosRoute: AuthenticatedAppVeiculosRoute,
  AuthenticatedAppViagensRoute: AuthenticatedAppViagensRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
